version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.7.3
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

    AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_key 
    # Setup GCP project and bucket information
    
    GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/keys/my-creds.json
    GCP_PROJECT_ID: citibike-zoomcamp
    GCS_BUCKET: citibike-data-lake-zoomcamp
    BASE_URL: https://s3.amazonaws.com/tripdata
    MONTHS: 202401,202402,202403,202404,202405,202406,202407,202408,202409,202410,202411,202412

    # 🔥 install dependencies
    _PIP_ADDITIONAL_REQUIREMENTS: >
      dbt-bigquery
      google-cloud-storage
      google-cloud-bigquery
      python-dotenv
      requests

  volumes:
    - ./dags:/opt/airflow/dags
    - ../ingestion:/opt/airflow/ingestion
    - ../dbt:/opt/airflow/dbt
    - ../dbt/keys:/opt/airflow/keys
    - ../ingestion/data:/opt/airflow/data

  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: >
      -c "airflow db migrate && airflow users create --username airflow --password airflow --firstname admin --lastname user --role Admin --email admin@example.com"
    depends_on:
      - postgres

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - airflow-init

  scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always
    depends_on:
      - airflow-init

volumes:
  postgres-db: