version: 2

sources:
  - name: raw
    database: citibike-zoomcamp
    schema: citibike
    tables:
      - name: trips_raw

models:
  - name: stg_trips
    description: "Cleaned CitiBike trips data"
    columns:
      - name: ride_id
        tests:
          - not_null
          - unique

      - name: trip_date
        tests:
          - not_null

      - name: trip_duration_sec
        description: "Trip duration in seconds"